apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
spec:
  encryptedData:
    token: AgA6SdQAsertTE2vkqRHTpLFHq4QWLTnjmVmTT2Ypn05fnJyWB/rxKmwKpaj6umR8IWqB0cYw/nPM4V0TS0k2alvaD1qtm8EjNdsXq8LC6mDg6mjWomPXwBNWp6p5PSsfm9eHqU98pcLHdpYirEnFoG+apOC0CYEu6DSboRf3Lh7HnQKRfgwNmcXMHgJ8VEgUL0VFEpt/CJ6QZ9nc5pPkHNwY4Y4glwfJkWnnZz/e76W5OBvY8d3RDJ2yLTU/9TTe14Lti0b0KQlJpvTfaWZKDVr6ruX52TrdSD5RqehDk7SniDRDfEH4WK0bsVgL2gO3hgwQ6Zh18aVo5GCk1vlg5v3xlBCiqAtAB0iTWI0TXFEm7V0z+CUnIOa2oOXeJmwxYcE720Rz97F9zksbW9q2mC1CwBgasmwdbInaNEpCuVeVscrOe0WvKTLfihwx+JyZ/1RXZuiYcFNmwI88N173+KlhtB4s/tHD+THhADnDb4o6lmzBMkb2G8Ha7IBsIsIIJVpElhiZ6pVyRaFXgPEosggnnM+vIIjhCWPh+uDpd4Akktb/wl749ruJWwEcgaTegPEnEddIXJ2dsKqIQ6VpdAi516pgfjIIFO6jGwxo88RA/OLh5GRb8zRKdTGY6YGUVX9Yh+VihVCfUwdl3gWY1W7Bpmq2W5P+XbaKLoACyCzpLJ0g7h+WNlS63IZ8FeclT3i5BTULUKo8b+Mt+ycc45xkJ7y8UUxO7S0zQp9oSuvSIRGyhDLJpgM
