apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cloudflare.yaml
helmCharts:
- repo: https://kubernetes-sigs.github.io/external-dns
  name: external-dns
  version: 1.20.0
  releaseName: external-dns
  namespace: external-dns
  valuesFile: values.yaml
