apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- repo: https://coredns.github.io/helm
  name: coredns
  version: 1.45.0
  releaseName: coredns
  namespace: coredns
  valuesFile: values.yaml
