httpRoute:
  enabled: true
  hostname: prowlarr.cecobask.com
image:
  repository: ghcr.io/home-operations/prowlarr
  tag: 2.3.0
livenessProbe:
  httpGet:
    path: /ping
    port: 9696
  initialDelaySeconds: 30
  timeoutSeconds: 10
name: prowlarr
persistence:
  enabled: true
  capacity: 1Gi
resources:
  requests:
    cpu: 10m
    memory: 180Mi
service:
  targetPort: 9696
volumeMounts:
- mountPath: /config
  name: config
volumes: ~
