apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: intel-device-plugins-operator
  repo: https://intel.github.io/helm-charts
  version: 0.34.1
  releaseName: intel-device-plugins-operator
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    manager:
      devices:
        gpu: true
    resources:
      limits: ~
- name: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts
  version: 0.34.1
  releaseName: intel-device-plugins-gpu
  namespace: kube-system
  valuesInline:
    name: gpudp
    sharedDevNum: 3
