apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  endpointslice.yaml: |
    apiVersion: discovery.k8s.io/v1
    kind: EndpointSlice
    metadata:
      name: home-assistant
      labels:
        kubernetes.io/service-name: home-assistant
    addressType: IPv4
    ports:
    - name: http
      port: 8123
    endpoints:
    - addresses:
      - 192.168.40.100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: home-assistant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: home-assistant
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - patch
  - update
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: home-assistant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: home-assistant
subjects:
- kind: ServiceAccount
  name: home-assistant
---
apiVersion: batch/v1
kind: Job
metadata:
  name: home-assistant
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: home-assistant
      volumes:
      - name: home-assistant
        configMap:
          name: home-assistant
      containers:
      - name: kubectl
        image: registry.k8s.io/kubectl:v1.34.1
        args:
        - apply
        - --filename=/home-assistant/endpointslice.yaml
        volumeMounts:
        - name: home-assistant
          mountPath: /home-assistant
