apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: haos
  labels:
    kubernetes.io/service-name: haos
addressType: IPv4
ports:
- port: 8123
endpoints:
- addresses:
  - 192.168.40.100
