apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: haos
spec:
  parentRefs:
  - name: cilium
    namespace: cilium
  hostnames:
  - haos.cecobask.com
  rules:
  - backendRefs:
    - name: haos
      port: 8123
