affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - pve2
httpRoute:
  enabled: false
  hostname: ~
  parentRefs:
  - name: envoy
    namespace: envoy-gateway
image:
  repository: ~
  tag: ~
livenessProbe: ~
name: ~
persistence:
  accessModes:
  - ReadWriteOnce
  backup:
    backblazeAccountID: 829ce80c-c7e7-44ca-9cd3-b3bb010754e1
    backblazeAccountKey: 1f7b53e2-70de-40b4-bced-b3bb0107ca6e
    backblazeRepository: 1c31c13f-4ad7-45bb-88c4-b3b8016414be
    resticPassword: fc256235-0bc9-4494-9568-b3b801637cf8
  capacity: ~
  enabled: false
  name: config
  storageClassName: proxmox
  volumeSnapshotClassName: proxmox
readinessProbe: ~
resources: ~
secretStoreRef:
  name: bitwarden
  kind: ClusterSecretStore
securityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  fsGroupChangePolicy: OnRootMismatch
service:
  port: 80
  targetPort: ~
startupProbe: ~
volumeMounts:
- mountPath: /config
  name: config
- mountPath: /media
  name: media
volumes:
- name: media
  persistentVolumeClaim:
    claimName: media
