apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
resources:
- namespace.yaml
helmCharts:
- repo: https://backube.github.io/helm-charts
  name: volsync
  version: 0.14.0
  releaseName: volsync
  namespace: volsync
  valuesFile: values.yaml
  apiVersions:
  - monitoring.coreos.com/v1/ServiceMonitor
