apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- repo: https://kubernetes-sigs.github.io/metrics-server
  name: metrics-server
  version: 3.13.0
  releaseName: metrics-server
  namespace: kube-system
  valuesFile: values.yaml
