httpRoute:
  enabled: true
  hostname: seerr.cecobask.com
image:
  repository: ghcr.io/seerr-team/seerr
  tag: sha-d0f029b
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /api/v1/status
    port: 5055
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: seerr
persistence:
  enabled: true
  capacity: 5Gi
resources:
  requests:
    cpu: 50m
    memory: 300Mi
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
service:
  targetPort: 5055
volumeMounts:
- mountPath: /app/config
  name: config
volumes: ~
