httpRoute:
  enabled: true
  hostname: jellyfin.cecobask.com
  timeouts:
    request: 3h
image:
  repository: ghcr.io/jellyfin/jellyfin
  tag: 10.11.2
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /health
    port: 8096
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: jellyfin
persistence:
  enabled: true
  capacity: 10Gi
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    gpu.intel.com/i915: 1000m
service:
  targetPort: 8096
