httpRoute:
  enabled: true
  hostname: jellyfin.cecobask.com
image:
  repository: ghcr.io/jellyfin/jellyfin
  tag: 10.11.2
livenessProbe:
  httpGet:
    path: /health
    port: 8096
  initialDelaySeconds: 30
  timeoutSeconds: 10
name: jellyfin
persistence:
  enabled: true
  capacity: 10Gi
service:
  targetPort: 8096
