apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: node-feature-discovery
  repo: oci://registry.k8s.io/nfd/charts
  version: 0.18.3
  releaseName: nfd
  includeCRDs: true
  namespace: kube-system
