apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
helmCharts:
- repo: https://vmware-tanzu.github.io/helm-charts
  name: velero
  version: 11.2.0
  releaseName: velero
  namespace: velero
  includeCRDs: true
  valuesFile: values.yaml
