apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backblaze
  namespace: velero
spec:
  encryptedData:
    cloud: AgAqVN27LIb1EIHF3uBPgC6jzGtO7bUDKBJOHF7F7n+3752TIH0iRGKl5Xif3sgmYNAWvIpbP3hKhN0AeVkH7QaGJXo5WakZA+j0oGEgvzDoZQbGrna0DpDKPIuJlzxSW0NErEH1JAaFzV4yS21qcb62bKbPU7NyKGDpI4m5GnAe9fx+TpzlB1WUTKbB++wlRhT4yH1WdzScGDQnWjsEsI8X8OC7g9fHGgtbnUKOoMs+epTcbrHu4mVFiXF8y6PXe/N8+DvgYSsKMtI6a75hocJ8KPBgeALH2D4x26Pq7H9xTNUwcEl8K4WIiw84UKjw2+M0NX+iTqj89UuzSkvzM6WFnkz79oQtye4z1oMAONs+o3s7uVTcTSG3WvgQDmR07mkHKYWfqnmAw1KO5lYeNgNGyksH7pjmQ5hK1QWob8x5xYD6hICcE4Djjo986SVJ5FEYe+9b372mDPthTriJQ/HI13VhQht0Yo4yZnjiFG2YT3MShXfjezoHDNnG8eV/PiqT+/mMAp1JiPKg5oqINEBZEWP/PqT5XNmkNBPn/tAGWbOOjOAEdBCNHO6cOK3U9VN+15fKRpWhPE1HKsTVOd84p+0Nb0R6oVPQSxO1Z3FynNNPIbZcLGxjHWVBVJGWcO1eTYZJhnRKC1MH2HNBNAUJxwKNmNVKB19UA1etage5ZvfYA7WoQ7KaSkaiU89Gu550AzCu3/X+98gPobbqA8IR5AMzuJWgUPE5ZGVb/55TVVcEC4MwHe9vPPnfvc6BecbufXlvxVmQqI2vjelfTmoPwMnC/vSLuVjtbC1PHUVn22zEjllHQgUS8g73lqjBA6y9Zs/jhK/IJR1b6jXc/0Z1
