credentials:
  existingSecret: backblaze
configuration:
  backupStorageLocation:
  - provider: velero.io/aws
    bucket: homelab-5678b8898f
    prefix: velero
    credential:
      name: backblaze
      key: cloud
    config:
      checksumAlgorithm: ""
      region: eu-central-003
      s3ForcePathStyle: true
      s3Url: https://s3.eu-central-003.backblazeb2.com
  features: EnableCSI
image:
  tag: v1.17.1
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.13.1
  volumeMounts:
  - mountPath: /target
    name: plugins
kubectl:
  image:
    repository: public.ecr.aws/bitnami/kubectl
snapshotsEnabled: false
