httpRoute:
  enabled: true
  hostname: qui.cecobask.com
image:
  repository: ghcr.io/autobrr/qui
  tag: v1.7.0
livenessProbe:
  httpGet:
    path: /healthz/liveness
    port: 7476
  initialDelaySeconds: 30
  timeoutSeconds: 10
name: qui
persistence:
  enabled: true
  capacity: 1Gi
securityContext:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  fsGroupChangePolicy: OnRootMismatch
service:
  port: 80
  targetPort: 7476
