apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: prometheus
spec:
  parentRefs:
  - name: envoy
    namespace: envoy-gateway
  hostnames:
  - prometheus.cecobask.com
  rules:
  - backendRefs:
    - name: prometheus-prometheus
      port: 9090
