apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- httproute.yaml
- namespace.yaml
- rules.yaml
helmCharts:
- repo: oci://ghcr.io/prometheus-community/charts
  name: kube-prometheus-stack
  version: 80.11.0
  releaseName: prometheus
  namespace: prometheus
  includeCRDs: true
  valuesFile: values.yaml
