apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/compare-options: ServerSideDiff=true
  argocd.argoproj.io/sync-options: ServerSideApply=true
resources:
- httproute.yaml
- namespace.yaml
- rules.yaml
helmCharts:
- repo: oci://ghcr.io/prometheus-community/charts
  name: kube-prometheus-stack
  version: 79.8.2
  releaseName: prometheus
  namespace: prometheus
  includeCRDs: true
  valuesFile: values.yaml
