alertmanager:
  enabled: false
cleanPrometheusOperatorObjectNames: true
commonLabels:
  cluster: homelab
coreDns:
  serviceMonitor:
    targetLabels:
    - cluster
defaultRules:
  create: false
fullnameOverride: prometheus
grafana:
  enabled: false
kubeControllerManager:
  serviceMonitor:
    targetLabels:
    - cluster
kubeEtcd:
  service:
    selector:
      component: kube-scheduler
  serviceMonitor:
    targetLabels:
    - cluster
kubelet:
  serviceMonitor:
    targetLabels:
    - cluster
kubeProxy:
  enabled: false
kubeScheduler:
  serviceMonitor:
    targetLabels:
    - cluster
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  customLabels:
    cluster: homelab
  prometheus:
    monitor:
      targetLabels:
      - cluster
prometheus:
  prometheusSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values: [ pve1 ]
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: proxmox
prometheusOperator:
  extraArgs:
  - --labels=cluster=homelab
  fullnameOverride: prometheus-operator
prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter
  prometheus:
    monitor:
      targetLabels:
      - cluster
