alertmanager:
  enabled: false
defaultRules:
  create: false
grafana:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
cleanPrometheusOperatorObjectNames: true
fullnameOverride: prometheus
commonLabels:
  cluster: homelab
coreDns:
  serviceMonitor:
    targetLabels:
    - cluster
kubeControllerManager:
  serviceMonitor:
    targetLabels:
    - cluster
kubeEtcd:
  serviceMonitor:
    targetLabels:
    - cluster
kubelet:
  serviceMonitor:
    targetLabels:
    - cluster
kubeScheduler:
  serviceMonitor:
    selector:
      matchLabels:
        component: kube-scheduler
    targetLabels:
    - cluster
kube-state-metrics:
  fullnameOverride: kube-state-metrics
  customLabels:
    cluster: homelab
  prometheus:
    monitor:
      targetLabels:
      - cluster
prometheusOperator:
  fullnameOverride: prometheus-operator
  extraArgs:
  - --labels=cluster=homelab
prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter
  prometheus:
    monitor:
      targetLabels:
      - cluster
