grafana:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  nodeSelector:
    topology.kubernetes.io/zone: pve1
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: proxmox
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
cleanPrometheusOperatorObjectNames: true
fullnameOverride: prometheus
alertmanager:
  fullnameOverride: alertmanager
kube-state-metrics:
  fullnameOverride: kube-state-metrics
prometheusOperator:
  fullnameOverride: prometheus-operator
prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter
