apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
secretGenerator:
- name: sealed-secrets-key
  namespace: sealed-secrets
  options:
    disableNameSuffixHash: true
  type: kubernetes.io/tls
  files:
  - tls.crt
  - tls.key
helmCharts:
- repo: https://bitnami-labs.github.io/sealed-secrets
  name: sealed-secrets
  version: 2.17.7
  releaseName: sealed-secrets
  namespace: sealed-secrets
  includeCRDs: true
  valuesFile: values.yaml
