apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
spec:
  parentRefs:
  - name: envoy
    namespace: envoy-gateway
  hostnames:
  - qbit.cecobask.com
  rules:
  - backendRefs:
    - name: qbittorrent
      port: 80
