apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 192.168.40.4
  name: qbittorrent-listening
  namespace: media
spec:
  ports:
  - name: tcp
    port: 40404
    protocol: TCP
  - name: udp
    port: 40404
    protocol: UDP
  selector:
    app: qbittorrent
  type: LoadBalancer
