httpRoute:
  enabled: true
  hostname: qbit.cecobask.com
image:
  repository: ghcr.io/home-operations/qbittorrent
  tag: 5.1.3
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 10
name: qbittorrent
persistence:
  enabled: true
  capacity: 1Gi
resources:
  requests:
    cpu: 10m
    memory: 64Mi
service:
  targetPort: 8080
