httpRoute:
  enabled: true
  hostname: qbit.cecobask.com
image:
  repository: ghcr.io/home-operations/qbittorrent
  tag: 5.1.3
livenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 10
  periodSeconds: 15
  tcpSocket:
    port: 8080
  timeoutSeconds: 5
name: qbittorrent
persistence:
  enabled: true
  capacity: 1Gi
resources:
  requests:
    cpu: 300m
    memory: 500Mi
service:
  targetPort: 8080
startupProbe:
  exec:
    command:
    - pidof
    - qbittorrent-nox
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
