apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bazarr
spec:
  parentRefs:
  - name: cilium
    namespace: cilium
  hostnames:
  - bazarr.cecobask.com
  rules:
  - backendRefs:
    - name: bazarr
      port: 80
