httpRoute:
  enabled: true
  hostname: bazarr.cecobask.com
image:
  repository: ghcr.io/home-operations/bazarr
  tag: 1.5.3
livenessProbe:
  httpGet:
    path: /api/system/ping
    port: 6767
  initialDelaySeconds: 30
  timeoutSeconds: 10
name: bazarr
persistence:
  enabled: true
  capacity: 1Gi
service:
  targetPort: 6767
