apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- storageclass.yaml
- volumesnapshotclass.yaml
helmCharts:
- repo: oci://ghcr.io/sergelogvinov/charts
  name: proxmox-csi-plugin
  version: 0.5.3
  releaseName: csi-proxmox
  namespace: csi-proxmox
  valuesFile: values.yaml
