apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: config.yaml
    remoteRef:
      key: 98532f9b-2bff-40ba-8286-b3b801610bfe
