apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgBf6ZyuMYaDm9V57wZ6j/j9AQi7uk/U6QkUo24c/BFOELHjDAOlBvyNjNJhfOrFj0hiBIJmr49M9LhQ27QjqkY/QbDdzUmQC4G0ciSjT7NSTP7nY0b7P+WfAEFB2bKGWQNMOwTSgH+b2fyjGIjdBsMRTkM2LLfTyUyjYDKf6LiYqVsXXZm0AJZf5GPM13GGJnCmzul0bWdIyMCl71rq/rmyviDvcHf9eciVRggd/GBnazsrDLiiab18p27MSCNMq+/MP5irehiFcLJC6ofLsM/D8iTXThg9uN5DLNxHEbTDIvqQk7fCc+dZvKVxBpOUHk/NKJpI8XCf22mP+KECpxJy67ljiuqJXAGQ/xNtqmroyhE3xP7daqg+wOA7/eiJXtVH0flzENkIO7ybxUU+f1iY1uIOOHKfMjD2e0T6GRorw/Snp47nKyihRYiH8GySL1eQ5sKoK2niE1TWxVbMV4CiXyGSvZCFZanDjIDkvkP7B8UBtUQU3nLGYMbv6VEWKaSOYXYlf19OTB2GV/pCYbUeBIEnpa8kj450Ku65TT1yfC7y8qZxSIj05v+AZKPdL9ElfmlZ4LqOYk7gbjoT4BXnBC185YLjh1JIVB/oWKOoKZmcl7mjLoCjxR/NV3wzyWcHzYZoV1goEdOoR+DW0OxToYDZm2yavk1OxKmiFPFxEN6lpuyfD1XPQHT8cYvJTKzA9L/LM1Cq51n3YwZFFq8Bol8fRsCt87veRkehrgXXoPGyUWurggWlizayUNVJZ5CbGUYrnejeXXj7VB6sm0/Uo8Z4TDcsoLYP6dk9fAo0R5/v3AwkjJLXTIql9nDAXyvreghQaBblAx2IQ0bk5ILASOziuM18mxg/4WnrJ39SW0oO1iDKQLZNVA==
