apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox
provisioner: csi.proxmox.sinextra.dev
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: local-lvm
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
