affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
controller:
  attacher:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
  plugin:
    resources:
      requests:
        cpu: 10m
        memory: 60Mi
  provisioner:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
  resizer:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
  snapshotter:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
existingConfigSecret: csi-proxmox
node:
  driverRegistrar:
    resources:
      requests:
        cpu: 10m
        memory: 30Mi
  plugin:
    resources:
      requests:
        cpu: 10m
        memory: 70Mi
tolerations:
- key: node-role.kubernetes.io/control-plane
  effect: NoSchedule
