storageClass:
- name: proxmox
  storage: local-lvm
- name: proxmox-retain
  storage: local-lvm
  reclaimPolicy: Retain
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
- key: node-role.kubernetes.io/control-plane
  effect: NoSchedule
existingConfigSecret: csi-proxmox
