apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudflare.yaml
- internal-ca.yaml
- namespace.yaml
helmCharts:
- repo: oci://quay.io/jetstack/charts
  name: cert-manager
  version: v1.19.1
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml
