apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- httproute.yaml
- namespace.yaml
- volumesnapshotclass.yaml
helmCharts:
- repo: https://charts.longhorn.io
  name: longhorn
  version: 1.10.1
  releaseName: longhorn
  namespace: longhorn-system
  valuesFile: values.yaml
