kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit
  template:
    metadata:
      labels:
        app: qbit
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: pve1
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: qbit
        image: ghcr.io/home-operations/qbittorrent:5.1.3
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbit
      - name: media
        persistentVolumeClaim:
          claimName: media
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qui
  template:
    metadata:
      labels:
        app: qui
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: pve1
      containers:
      - name: qui
        image: ghcr.io/autobrr/qui:v1.7.0
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qui
      - name: media
        persistentVolumeClaim:
          claimName: media
