apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbit
spec:
  parentRefs:
  - name: cilium
    namespace: cilium
  hostnames:
  - qbit.cecobask.com
  rules:
  - backendRefs:
    - name: qbit
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qui
spec:
  parentRefs:
  - name: cilium
    namespace: cilium
  hostnames:
  - qui.cecobask.com
  rules:
  - backendRefs:
    - name: qui
      port: 7476
