kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbit
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-proxmox
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qui
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-proxmox
