apiVersion: v1
kind: Service
metadata:
  name: qbit
spec:
  selector:
    app: qbit
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qui
spec:
  selector:
    app: qui
  ports:
  - port: 7476
