apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cecobask.com
  namespace: envoy-gateway
spec:
  dnsNames:
  - "*.cecobask.com"
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: cecobask.com
