apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway.yaml
- namespace.yaml
helmCharts:
- repo: oci://docker.io/envoyproxy
  name: gateway-helm
  version: v1.6.0
  releaseName: envoy-gateway
  namespace: envoy-gateway
