apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
resources:
- certificate.yaml
- gateway.yaml
- namespace.yaml
helmCharts:
- repo: oci://docker.io/envoyproxy
  name: gateway-crds-helm
  version: v1.6.0
  releaseName: envoy-gateway-crds
  namespace: envoy-gateway
  valuesFile: values.yaml
- repo: oci://docker.io/envoyproxy
  name: gateway-helm
  version: v1.6.0
  releaseName: envoy-gateway
  namespace: envoy-gateway
