apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- repo: oci://ghcr.io/prometheus-community/charts
  name: prometheus-operator-crds
  version: 25.0.0
  releaseName: prometheus-operator-crds
