apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- media.yaml
- platform.yaml
secretGenerator:
- name: bitwarden
  namespace: external-secrets
  files:
  - token=bitwarden-token
  options:
    disableNameSuffixHash: true
