httpRoute:
  enabled: true
  hostname: sonarr.cecobask.com
  timeouts:
    request: 3m
image:
  repository: ghcr.io/home-operations/sonarr
  tag: 4.0.16
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /ping
    port: 8989
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: sonarr
persistence:
  enabled: true
  capacity: 5Gi
resources:
  requests:
    cpu: 300m
    memory: 350Mi
service:
  targetPort: 8989
