apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cecobask.com
  namespace: traefik
spec:
  dnsNames:
  - "*.cecobask.com"
  - cecobask.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
  secretName: cecobask.com
