apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
- certificate.yaml
- namespace.yaml
helmCharts:
- repo: https://traefik.github.io/charts
  name: traefik
  version: 37.2.0
  releaseName: traefik
  namespace: traefik
  valuesFile: values.yaml
