providers:
  kubernetesCRD:
    enabled: false
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false
gateway:
  name: traefik
  listeners:
    websecure:
      port: 8443
      protocol: HTTPS
      certificateRefs:
      - name: cecobask.com
      namespacePolicy:
        from: All
logs:
  access:
    enabled: true
    format: json
  general:
    level: DEBUG
    format: json
service:
  annotations:
    lbipam.cilium.io/ips: 192.168.40.3
image:
  tag: v3.6.0
