httpRoute:
  enabled: true
  hostname: radarr.cecobask.com
image:
  repository: ghcr.io/home-operations/radarr
  tag: 6.0.3
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /ping
    port: 7878
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: radarr
persistence:
  enabled: true
  capacity: 5Gi
resources:
  requests:
    cpu: 100m
    memory: 300Mi
service:
  targetPort: 7878
