apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pool.yaml
helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: v1.18.5
  releaseName: cilium
  namespace: cilium
  valuesFile: values.yaml
