apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
- pool.yaml
- namespace.yaml
- gateway.yaml
helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: v1.18.3
  releaseName: cilium
  namespace: cilium
  valuesFile: values.yaml
  valuesInline:
    l2announcements:
      enabled: true
    gatewayAPI:
      enabled: true
      gatewayClass:
        create: "false"
      secretsNamespace:
        create: false
        name: cilium
