apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
- base/namespace.yaml
- gateway.yaml
- pool.yaml
helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: v1.18.4
  releaseName: cilium
  namespace: cilium
  valuesFile: base/values.yaml
  additionalValuesFiles:
  - values.yaml
