apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pool.yaml
- namespace.yaml
helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: v1.18.3
  releaseName: cilium
  namespace: cilium
  valuesFile: values.yaml
