apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pool.yaml
helmCharts:
- repo: https://helm.cilium.io
  name: cilium
  version: v1.18.2
  releaseName: cilium
  namespace: kube-system
  valuesFile: values.yaml
