global:
  image:
    tag: v3.1.9
configs:
  cm:
    kustomize.buildOptions: --enable-helm
  params:
    server.insecure: true
dex:
  enabled: false
notifications:
  enabled: false
server:
  httproute:
    enabled: true
    parentRefs:
    - name: traefik
      namespace: traefik
    hostnames:
    - argocd.cecobask.com
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.cecobask.com
