crds:
  enabled: false
kubeProxy:
  enabled: false
prometheus:
  nodeSelector:
    topology.kubernetes.io/zone: pve1
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: proxmox
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
