apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitwarden.yaml
- namespace.yaml
helmCharts:
- repo: https://charts.external-secrets.io
  name: external-secrets
  version: 1.2.1
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: values.yaml
