apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true
resources:
- bitwarden.yaml
- namespace.yaml
helmCharts:
- repo: https://charts.external-secrets.io
  name: external-secrets
  version: 1.2.0
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: values.yaml
