bitwarden-sdk-server:
  enabled: true
  image:
    tls:
      secretName: bitwarden-sdk-server
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
resources:
  requests:
    cpu: 10m
    memory: 128Mi
webhook:
  certManager:
    cert:
      issuerRef:
        kind: ClusterIssuer
        name: internal-ca
    enabled: true
  lookaheadInterval: 48h
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
