bitwarden-sdk-server:
  enabled: true
  image:
    tls:
      secretName: bitwarden-sdk-server
webhook:
  certManager:
    cert:
      issuerRef:
        kind: ClusterIssuer
        name: internal-ca
    enabled: true
  lookaheadInterval: 48h
