apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
helmCharts:
- repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  name: csi-driver-smb
  version: 1.19.1
  releaseName: csi-smb
  namespace: csi-smb
  valuesFile: values.yaml
