windows:
  enabled: false
storageClasses:
- name: media
  parameters:
    source: //nas.cecobask.com/media
    csi.storage.k8s.io/node-stage-secret-name: csi-smb
    csi.storage.k8s.io/node-stage-secret-namespace: csi-smb
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - noperm
  - mfsymlinks
  - noserverino
