- Bookmarks:
  - Backblaze:
    - description: S3 cloud storage
      href: https://backblaze.com
      icon: backblaze
  - Homelab:
    - description: Source code on GitHub
      href: https://github.com/cecobask/homelab
      icon: github-light
  - TorrentLeech:
    - description: Private torrent tracker
      href: https://torrentleech.org
      icon: mdi-pirate
