apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: media
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: bazarrToken
    remoteRef:
      key: 6809034a-de77-4c93-b5ae-b3d700b9b2cf
  - secretKey: jellyfinToken
    remoteRef:
      key: 0a2ecaf9-b8e0-4a99-a312-b3d700bf850f
  - secretKey: prowlarrToken
    remoteRef:
      key: 74a07108-8609-47dc-99c9-b3d700c61d89
  - secretKey: qbittorrentUsername
    remoteRef:
      key: 045d88a3-7967-4509-8af3-b3d700c8a6ae
  - secretKey: qbittorrentPassword
    remoteRef:
      key: 419ebff6-30b0-48ea-8b07-b3d700c8d74a
  - secretKey: radarrToken
    remoteRef:
      key: e5963f45-7c4b-4f9b-be2d-b3d700ca08ec
  - secretKey: seerrToken
    remoteRef:
      key: dea27f9f-bcad-4701-b5f8-b3d700cc3de6
  - secretKey: sonarrToken
    remoteRef:
      key: 380651f7-ff04-4bdf-a3e7-b3d700cb92e7
