- Media:
  - Bazarr:
      description: Subtitle management for movies and TV shows
      href: https://bazarr.cecobask.com
      icon: bazarr
  - Jellyfin:
      description: Media server for streaming movies and TV shows
      href: https://jellyfin.cecobask.com
      icon: jellyfin
  - Profilarr:
      description: Quality profile and custom format manager for Radarr and Sonarr
      href: https://profilarr.cecobask.com
      icon: profilarr
  - Prowlarr:
      description: Indexer manager for Radarr and Sonarr
      href: https://prowlarr.cecobask.com
      icon: prowlarr
  - qBittorrent:
      description: BitTorrent client for downloading media
      href: https://qbit.cecobask.com
      icon: qbittorrent
  - Qui:
      description: Alternative BitTorrent web user interface
      href: https://qui.cecobask.com
      icon: qui
  - Radarr:
      description: Movie collection manager
      href: https://radarr.cecobask.com
      icon: radarr
  - Seerr:
      description: Request and discovery platform for movies and TV shows
      href: https://seerr.cecobask.com
      icon: jellyseerr
  - Sonarr:
      description: TV show collection manager
      href: https://sonarr.cecobask.com
      icon: sonarr
- Platform:
  - Argo CD:
      description: Declarative continuous delivery tool
      href: https://argocd.cecobask.com
      icon: argo-cd
  - Grafana:
      description: Data visualization platform
      href: https://grafana.cecobask.com
      icon: grafana
  - Prometheus:
      description: Monitoring system
      href: https://prometheus.cecobask.com
      icon: prometheus
- Miscellaneous:
  - Home Assistant:
      description: Home automation platform
      href: https://haos.cecobask.com
      icon: home-assistant
  - Proxmox 1:
      description: Virtualization platform
      href: https://pve1.cecobask.com:8006
      icon: proxmox
  - Proxmox 2:
      description: Virtualization platform
      href: https://pve2.cecobask.com:8006
      icon: proxmox
  - Proxmox 3:
      description: Virtualization platform
      href: https://pve3.cecobask.com:8006
      icon: proxmox
  - UniFi:
      description: Network management, surveillance, and storage solutions
      href: https://unifi.ui.com
      icon: unifi
