- Media:
  - Bazarr:
      description: Subtitle manager
      href: https://bazarr.cecobask.com
      icon: bazarr
  - Jellyfin:
      description: Media server
      href: https://jellyfin.cecobask.com
      icon: jellyfin
  - Profilarr:
      description: Quality profile manager
      href: https://profilarr.cecobask.com
      icon: profilarr
  - Prowlarr:
      description: Indexer manager
      href: https://prowlarr.cecobask.com
      icon: prowlarr
  - qBittorrent:
      description: BitTorrent client
      href: https://qbit.cecobask.com
      icon: qbittorrent
  - Qui:
      description: BitTorrent web user interface
      href: https://qui.cecobask.com
      icon: qui
  - Radarr:
      description: Movie manager
      href: https://radarr.cecobask.com
      icon: radarr
  - Seerr:
      description: Movie and TV show request platform
      href: https://seerr.cecobask.com
      icon: jellyseerr
  - Sonarr:
      description: TV show manager
      href: https://sonarr.cecobask.com
      icon: sonarr
- Platform:
  - Argo CD:
      description: Declarative continuous delivery platform
      href: https://argocd.cecobask.com
      icon: argo-cd
  - Grafana:
      description: Data visualization platform
      href: https://grafana.cecobask.com
      icon: grafana
  - Prometheus:
      description: Monitoring system
      href: https://prometheus.cecobask.com
      icon: prometheus
- Miscellaneous:
  - Home Assistant:
      description: Home automation platform
      href: https://haos.cecobask.com
      icon: home-assistant
  - Proxmox 1:
      description: Server virtualization platform
      href: https://pve1.cecobask.com:8006
      icon: proxmox-light
  - Proxmox 2:
      description: Server virtualization platform
      href: https://pve2.cecobask.com:8006
      icon: proxmox-light
  - Proxmox 3:
      description: Server virtualization platform
      href: https://pve3.cecobask.com:8006
      icon: proxmox-light
  - UniFi:
      description: Network, storage, and surveillance platform
      href: https://unifi.ui.com
      icon: unifi
