env:
- name: HOMEPAGE_ALLOWED_HOSTS
  value: homepage.cecobask.com
- name: HOMEPAGE_VAR_BAZARR_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: bazarrToken
- name: HOMEPAGE_VAR_JELLYFIN_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: jellyfinToken
- name: HOMEPAGE_VAR_PROWLARR_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: prowlarrToken
- name: HOMEPAGE_VAR_QBITTORRENT_USERNAME
  valueFrom:
    secretKeyRef:
      name: homepage
      key: qbittorrentUsername
- name: HOMEPAGE_VAR_QBITTORRENT_PASSWORD
  valueFrom:
    secretKeyRef:
      name: homepage
      key: qbittorrentPassword
- name: HOMEPAGE_VAR_RADARR_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: radarrToken
- name: HOMEPAGE_VAR_SEERR_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: seerrToken
- name: HOMEPAGE_VAR_SONARR_TOKEN
  valueFrom:
    secretKeyRef:
      name: homepage
      key: sonarrToken
- name: HOMEPAGE_VAR_ARGOCD_TOKEN
  valueFrom:
    secretKeyRef:
      name: argocd-readonly
      key: token
httpRoute:
  enabled: true
  hostname: homepage.cecobask.com
image:
  repository: ghcr.io/gethomepage/homepage
  tag: dev
livenessProbe:
  failureThreshold: 5
  httpGet:
    httpHeaders:
    - name: Host
      value: homepage.cecobask.com
    path: /api/healthcheck
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 10
name: homepage
resources:
  requests:
    cpu: 100m
    memory: 300Mi
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
service:
  targetPort: 3000
volumeMounts:
- mountPath: /app/config
  name: config
- mountPath: /app/config/logs
  name: logs
volumes:
- name: config
  configMap:
    name: homepage
- name: logs
  emptyDir:
    sizeLimit: 500Mi
