apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- httproute.yaml
- namespace.yaml
- secret.yaml
helmCharts:
- repo: https://grafana.github.io/helm-charts
  name: grafana
  version: 10.2.0
  releaseName: grafana
  namespace: grafana
  valuesFile: values.yaml
